### ISSUE TITLE
AWS Path exception

### ISSUE THREAD

**Issue by T1000v2** [FoundatioFx/Foundatio.AWS#272]
Hi,

1. Please implement better exception handling for deletion (for example despite of proper deletion still it raised exception without informing me how many objects were removed)
2. Please add support for multiple levels of wildcard e.g.` s3://mybucket/folder/*ewewe/20190812/*/*file01?1?`

**Comment by ejsmith** [comment]
@T1000v2 yeah, if you are seeing specific issues, we would love to see a PR addressing those issues. As far as multiple levels of wildcards, I think that might end up being a pretty big performance hit and I think we are also relying on underlying S3 features which don't have that ability.

**Comment by T1000v2** [comment]
> 
> 
>     1. Can you please give us additional information about this, what errors did you run into with deletes?
> 
>     2. We'd be willing to accept a pr for this behavior. We just submit delete requests to aws to delete content after getting a page of results. I'd recommend trying to add a unit tests for this scenario to the Foundatio.AWS project and stepping through the logic.

**Comment by T1000v2** [comment]
@niemyjski 
Resoponse is standard
>  {"The XML you provided was not well-formed or did not validate against our published schema"}

and then I see manually that in fact path was cleared. So error/exception and the same action completed. Total mess.

**Comment by niemyjski** [comment]
I’m guessing the path submitted wasn’t valid. Can you submit a patch with failing unit test/fix?

**Comment by T1000v2** [comment]
@ejsmith I don't think that with up to 1k in batch strings regex would be an issue ever ...

@niemyjski 
1st path: test/2/otherfolder/yetanother/2foldertodelete2/2object2
2nd path: test/22/otherfolder2/yetanother2/2foldertodelete2/2object2
3rd path: test/223/otherfolder3/yetanother3/2foldertodelete2/2object2
4th path: test/2/otherfolder123/yetanother456/2foldertodelete2/2object2

1. Naming in example looks strange but its for reason especially having "2" in names
2. I want to delete "2foldertodelete" with all objects inside for (test/2) no matter what are names of others folders between them.
3. Result I need from  deletion should be erased "2foldertodelete2/2object2" from first and 4th path
2nd and 3rd path despite it has same "2foldertodelete2" should stay untouched (because 22 and 23 is not "2")

I'm using:
storage.DeleteFilesAsync(@"test/2/*2foldertodelete2*");

First of all not sure if that's proper but what I have observed as mentioned earlier.
IMHO /2/ should separate there fully from 2* names like 222
Total mess, when more files are inside "22" I'm getting exceptions.
When there is alone 1st path only it works without an exception.

**Comment by T1000v2** [comment]
Please let me know first how use wildcard properly on this simple example:
1. `/test/1/*objecttodelete`
2. /test/11/*objecttodelete'

How to delete all with name *objecttodelete but untouched path 2 ("11")
Looks like currently /1/* is also attaching all with 1* but / should separate it and /11/ should not be included.

**Comment by niemyjski** [comment]
Can you submit a unit test for both of these issues and we'll take a closer look

**Comment by T1000v2** [comment]
> 
> 
> Can you submit a unit test for both of these issues and we'll take a closer look

As for first problem about path and regex it was probably my wrong testing and false alarm
As for second, just repeated the same on new sample structure:

It's console app not test unit, it has just one line of call your code(I cannot share my s3) :
With PAGE_SIZE = 10; it does not work fully, with larger like 100, 200 works as expected, but it's not the solution since accordingly when will be 2-3k objects inside even max 1k will not be enough and same error will appear.

Small zip attached url(registration not needed, open url):
https://1drv.ms/u/s!AsE67YQqfruAhFtzDdAYJGcVssfL?e=E8exFp
Steps:
1. Read info
2. Upload this test folder to your bucket and test with same wildcard path .

**Comment by niemyjski** [comment]
Can you add a test to the test project, for security reasons we don't like downloading zips. We don't need any of your authentication or anything. Just a failing test.

**Comment by T1000v2** [comment]
I haven't got ant test, I use real world example one line of code which is inside zip info.txt so not sure what you need to attach?
Also how without folder structure are you going to make test? I prepared this for you to be as clear as possible so reproduce is possible with less than 3 minutes.
I also don't like too much and I understand but It's small clean simple zip file with minor sized txt files and folders struct, notthing to worry about.

**Comment by T1000v2** [comment]
Can you check?

**Comment by niemyjski** [comment]
Can you just paste the code you used in the small sample in a code snippet here. You can do this with the ``` block. Ideally it really would be nice & helpful to have a unit test for this, it's really simple to get up and running.

**Comment by T1000v2** [comment]
@niemyjski 
Exactly the same as you see in archive: Here you are:  `await storage.DeleteFilesAsync(@"test/1/*2020-06-30*")`

Point of my post is not my code, since it's trivial, just one line + own s3 storage option credentials.
I do not use all procedures from your testing like upload listing and so on but just  delete with regex pattern.

1. I've uploaded folder/files structire all those manually via panel AWS to make sure all was properly(not using your code)
2. Copying and pasting folder/objects structure does not make sense - it would be too much pain for you to replicate -  instead I attached it in previous link archive so it's enough to unzip and upload whole folder to any of your test bucket and try with that pattern delete.

**Comment by niemyjski** [comment]
I didn't open the zip for security concerns and I don't test using s3, we use docker with local stack so it's impossible for me to drop files there, that is why a test or a snippet of actual that creates the files and try to get the files is important.

**Comment by T1000v2** [comment]
LOL, 
I come here for help indeed but this works both ways in case of making your code better.
I've never heard so ridiculous explanations before.
Even everyday computer user (not even geek or superuser) knows how to open zip archives, and programmer don't know that there is NO even minor security risk with just extracting zip archive?

If I don't know about this code quality why am I supposed to increase only potential point of failrues by uploading it with test??

So I wanted to make as simple as possible and test DELETE only nothing else, 
I'm talking about s3 from the begening I don't care about local testing.
I have wasted already too much of my valuable time to put energy into this to make this reproducable for you, but you are not going to help at all.  I found experience with you and your project one of the most terrible experience.

**Comment by niemyjski** [comment]
Please respect the code of conduct for a positive community. This is an open source project that is worked on in OUR FREE time, we asked for a simple unit test or code snippet that we've yet to get. We want a community participation (which we go to great lengths to ensure everyone feels welcome, and it's easy to contribute to)  instead of multiple people requesting via private email for help in solving this, we are all developers and could have contributed a test and sped up the whole process.  We wanted a unit test so we could run and see this behavior you are seeing which also helps contribute to our test coverage. We are grateful you reached out, but more can be done to help this community and others by actively contributing anything be it docs, code snippets or unit tests.

I've looked into this and even added simple unit tests that ensure this is working (https://github.com/FoundatioFx/Foundatio/blob/b807c718490c95b517ebb622b12ed5d0f9daf173/src/Foundatio.TestHarness/Storage/FileStorageTestsBase.cs#L275-L300), which it's not a path exception it's supporting multiple directory wild cards. If your wild card is bad it won't work and it's throwing an exception. What could be done is research what all the wild card combinations are for paths and write a validator or xml docs on what is accepted.

**Comment by niemyjski** [comment]
For doing wild cards on multiple paths may not be supported (I'm not sure of the exact syntax, I'd look it up in AWS) but it is at least on a single path (e.g., folder/*skipanyparentfolder_butmatchesthisfoldername*). Even single path wildcards are not supported by Directory.EnumerateFiles(). If you can comment back the syntax I can try adding a test for this or feel free to add one or submit a pr for this functionality). It should work today in AWS as long as the syntax is correct and AWS supports it. In the past, I haven't yet seen a storage provider support this but I didn't actively go looking to do this.

**Comment by T1000v2** [comment]
Didn't wanted to sound rude, but you can understand my frustration..thx for info.  Anyway Ok next time I will follow your rules no matter about my view on this.

Test worked for you because details there are important, either put at least 30-50 files and few folders or just upload my folder and test with PAGE SIZE =10, (with page size like 100 it will work without exception)

Please notice that to make test unit clear and simple it's good to have like you did it actually(few lines clean&clear )
When I'd add my folder structure added with your put code to add bunch of files/folders it will look overloaded and messy
That's why I insisted to just upload whole already prepared folder to quickly check this.

**Comment by niemyjski** [comment]
I'm not sure where you are seeing page size on a delete, I changed the page_size constant to 2 inside the delete files implementation (1 throws an error due to being a bad request) and it worked.

**Comment by niemyjski** [comment]
If you clone/fork this project and open the project in Visual Studio or Rider, you can build the project without any configuration. Then in terminal type `docker-compose up` to startup localstack which emulates s3 locally and then you can run any test in the project If you want to play around with it.

**Comment by T1000v2** [comment]
page size I mean to `ListObjectsV2Request` of course anyway this parameter changes everything during my test (10 = exceptions and only one folder with date deleted, with 100 no exception and all deleted properly)

**Comment by niemyjski** [comment]
We just found and fixed some issues with the s3 where it could get a full page of results which had no matches and would blow up. I think this may be the issue you were running into. Can you try a nightly.

**Comment by niemyjski** [comment]
Can you please try a nightly and let us know if this fixes the issue.

**Comment by T1000v2** [comment]
Thanks, I will check soon today. ps. What is the proper usage of test, code base is in TestHarness while the latest code of AWS is in different project repo which do not contain base/body, what is the most correct way of usage of this?

**Comment by niemyjski** [comment]
We don't have a mono repo so we share all common tests for all our
implementations in the main repo and reference those in the child projects
like AWS. If you are just testing something in AWS you can always copy or
make a new test in the AWS project to check something out without modifying
the test harness.

**Comment by T1000v2** [comment]
I've edited one of my too emotional posting, just was frustrated because even my best intentions was not enough. 
Anyway after quick test result -  Worked - thank you! I'll keep more deep testing tonight.

**Comment by niemyjski** [comment]
All is well! Thanks for the update!
